on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - uses: actions/checkout@v1

      - name: Run action action
        id: var
        uses: ./
        with:
          file: './action.yml'
          key-path: '["inputs"]'

      - name: Get action output
        run: echo "${{ steps.var.outputs.data }}"
